---

- hosts: all 
  become: true
  tasks: 

  - name: Ensure apache is at the latest version
    apt:
      name: apache2


  - name: Ensure apache is running
    ansible.builtin.service:
        name: apache2
        state: started
